### ISSUE TITLE
Unable to export products to Algolia

### ISSUE THREAD

**Issue by claudio-uey** [w3bdesign/wp-algolia-woo-indexer#192]
I have followed the instructions:

Set my `application id`, `Admin API Key` and index name in the settings. When I click on send products to algolia I get a critical error:

> Detalles Del Error
> Se produjo un error de tipo E_ERROR en la línea 210 del archivo /var/www/html/web/app/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php. Mensaje de error: Uncaught Algolia\AlgoliaSearch\Exceptions\BadRequestException: Invalid Application-ID or API key in /var/www/html/web/app/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php:210
> Stack trace:
> #0 /var/www/html/web/app/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php(158): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->handleResponse(Object(GuzzleHttp\Psr7\Response), Object(Algolia\AlgoliaSearch\Http\Psr7\Request))
> #1 /var/www/html/web/app/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php(78): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->request('GET', '/1/keys', Object(Algolia\AlgoliaSearch\RequestOptions\RequestOptions), Array, 5)
> #2 /var/www/html/web/app/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/SearchClient.php(205): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->read('GET', '/1/keys', Object(Algolia\AlgoliaSearch\RequestOptions\RequestOptions))
> #3 /var/www/html/web/app/plugins/algolia-woo-indexer/classes/class-send-products.php(71): Algolia\AlgoliaSearch\SearchClient->listApiKeys()
> #4 /var/www/html/web/app/plugins/algolia-woo-indexer/classes/class-send-products.php(150): Algowoo\Algolia_Send_Products::can_connect_to_algolia()
> #5 /var/www/html/web/app/plugins/algolia-woo-indexer/classes/class-algolia-woo-indexer.php(211): Algowoo\Algolia_Send_Products::send_products_to_algolia()
> #6 /var/www/html/web/wp/wp-includes/class-wp-hook.php(310): Algowoo\Algolia_Woo_Indexer::maybe_send_products('')
> #7 /var/www/html/web/wp/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
> #8 /var/www/html/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
> #9 /var/www/html/web/wp/wp-admin/admin.php(175): do_action('admin_init')
> #10 /var/www/html/web/wp/wp-admin/options-general.php(10): require_once('/var/www/html/w...')
> #11 {main}
>   thrown

  
  The error claims `Invalid Application-ID or API key` but I have triple checked the API keys. I made sure to use the ADMIN API key.
  
I am using the following versions:
WordPress 6.3.2
Active theme: Storefront Child Theme (version 1.0.0)
Plugin actual: Algolia WooCommerce Indexer (version 1.0.7) *it is latest commit in master
Versión de PHP: 8.1.27

I also verified I have mbstring, curl and mbregex installed and loaded.

I also tried with a non-admin key with all the permissions available.

Not sure what could be the issue. Any help would be greatly appreciated.

**Comment by w3bdesign** [comment]
@claudio-uey 

Just tested with version 1.0.6 of the plugin and version 7.4.0 of Woocommerce and Wordpress 6.4.3. 

It seems to work without any errors.

I would try downgrading or doublechecking the key and application ID. 

You need the following settings for it to work:

Application ID
Admin API Key
Index name

If you want to be 100% sure you can just modify the plugin .php file and hardcode the ID, key and index name, and see if it makes any difference. It should be sufficient for testing, but it is not recommended to do it in a live encirionment.
